# Copyright (C) Microarray
# MicroArray Fprint Driver Code
# MAKEFILE
# Date: 2017-07-21
# Version: for_intel_v4.0.06
# Author: guq
# Contact: guq@microarray.com.cn

obj-y	+= madev_tee.o x86-settings.o