subdir-ccflags-y := \
	-Idrivers/misc/sprdwcn_bsp/sc23xx/include \
	-Idrivers/misc/sprdwcn_bsp/sc23xx/boot \
	-Idrivers/misc/sprdwcn_bsp/sc23xx/platform \
	-Idrivers/misc/sprdwcn_bsp/sc23xx/platform/rf
obj-$(CONFIG_SC23XX) += wcn_bus.o
obj-$(CONFIG_PCIEHAL) += pcie/
obj-$(CONFIG_SDIOHAL) += sdio/
obj-$(CONFIG_WCN_SIPC) += sipc/
obj-$(CONFIG_WCN_SLP) += sleep/
obj-$(CONFIG_WCN_BOOT) += platform/
obj-$(CONFIG_SC2342_INTEG) += boot/
obj-$(CONFIG_MARLIN3_GNSS) += gnss/
obj-$(CONFIG_WCN_PLATFORM) += platform/
