dtb-$(CONFIG_ARCH_SPRD) += sc9836-openphone.dtb \
	sp9850s-1h10-native.dtb \
	sp9850s-2h10-native.dtb \
	sp9860g-1h10-native.dtb \
	sp9860g-1h10-al.dtb \
	sp9860g-2h10-native.dtb \
	sp9860g-1h10-3g.dtb \
	sp9860g-1h10-3gfhd.dtb \
	ss_whale2_j7-native.dtb \
	sp9850kh-smt-1h10.dtb \
	sp9850kh-smt-1h10-a53only.dtb \
	sp9850kh-smt-1h10-singlethread.dtb \
	sp9850kh-smt-1h10-isolatecpu.dtb \
	sp9850kh-smt-2c20.dtb \
	sp9850kh-smt-fpga.dtb \
	sp9850kh-smt-vdk.dtb \
	sp9850kh-smt-zebu.dtb \
	sp9862-vdk.dtb \
	sp9862-haps.dtb \
	sp9835_haps.dtb \
	sp9855a-vdk.dtb \
	sp9855a-haps.dtb \
	sp9863a-1h10-native.dtb\
	sp9863a-2h10-native.dtb\
	sp9832e-1h10-native.dtb\
	sp9850e-1h10-native.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
